---
- node:
    id: awx-1

- log-level: info

- local-only: null

- control-service:
    service: control
    filename: /var/run/receptor/receptor.sock
    permissions: '0666'

- work-command:
    worktype: local
    command: ansible-runner
    params: worker
    allowruntimeparams: true
